from typing import List


map_names: List[str] = [
    'The Slipgate Complex (E1M1)',
    'Castle of the Damned (E1M2)',
    'The Necropolis (E1M3)',
    'The Grisly Grotto (E1M4)',
    'Gloom Keep (E1M5)',
    'The Door to Chthon (E1M6)',
    'The House of Chthon (E1M7)',
    'Ziggurat Vertigo (E1M8)',
    'The Installation (E2M1)',
    'The Ogre Citadel (E2M2)',
    'The Crypt of Decay (E2M3)',
    'The Ebon Fortress (E2M4)',
    'The Wizard\'s Manse (E2M5)',
    'The Dismal Oubliette (E2M6)',
    'The Underearth (E2M7)',
    'Termination Central (E3M1)',
    'The Vaults of Zin (E3M2)',
    'The Tomb of Terror (E3M3)',
    'Satan\'s Dark Delight (E3M4)',
    'The Wind Tunnels (E3M5)',
    'Chambers of Torment (E3M6)',
    'The Haunted Halls (E3M7)',
    'The Sewage System (E4M1)',
    'The Tower of Despair (E4M2)',
    'The Elder God Shrine (E4M3)',
    'The Palace of Hate (E4M4)',
    'Hell\'s Atrium (E4M5)',
    'The Pain Maze (E4M6)',
    'Azure Agony (E4M7)',
    'The Nameless City (E4M8)',
    'Shub-Niggurath\'s Pit (END)',
]
