from typing import List
from BaseClasses import TypedDict

class ConnectionDict(TypedDict, total=False):
    target: str

class RegionDict(TypedDict, total=False):
    name: str
    connects_to_hub: bool
    episode: int
    connections: List[ConnectionDict]


regions:List[RegionDict] = [
    {"name": "The Slipgate Complex (E1M1) Main",
     "connects_to_hub": True,
     "episode": 1,
     "connections":[]},

    {"name": "Castle of the Damned (E1M2) Main",
     "connects_to_hub": True,
     "episode": 1,
     "connections":[{"target":"Castle of the Damned (E1M2) Silver"}]},
    {"name": "Castle of the Damned (E1M2) Silver",
     "connects_to_hub": False,
     "episode": 1,
     "connections":[{"target":"Castle of the Damned (E1M2) Main"}]},

    {"name": "The Necropolis (E1M3) Main",
     "connects_to_hub": True,
     "episode": 1,
     "connections":[{"target":"The Necropolis (E1M3) Gold"}]},
    {"name": "The Necropolis (E1M3) Gold",
     "connects_to_hub": False,
     "episode": 1,
     "connections":[{"target":"The Necropolis (E1M3) Main"}]},

    {"name": "The Grisly Grotto (E1M4) Main",
     "connects_to_hub": True,
     "episode": 1,
     "connections":[{"target":"The Grisly Grotto (E1M4) Silver"}]},
    {"name": "The Grisly Grotto (E1M4) Silver",
     "connects_to_hub": False,
     "episode": 1,
     "connections":[{"target":"The Grisly Grotto (E1M4) Main"}]},

    {"name": "Gloom Keep (E1M5) Main",
     "connects_to_hub": True,
     "episode": 1,
     "connections":[{"target":"Gloom Keep (E1M5) Silver"}]},
    {"name": "Gloom Keep (E1M5) Silver",
     "connects_to_hub": False,
     "episode": 1,
     "connections":[
        {"target":"Gloom Keep (E1M5) Silver"},
        {"target":"Gloom Keep (E1M5) Gold"}]},
    {"name": "Gloom Keep (E1M5) Gold",
     "connects_to_hub": False,
     "episode": 1,
     "connections":[{"target":"Gloom Keep (E1M5) Main"}]},

    {"name": "The Door to Chthon (E1M6) Main",
     "connects_to_hub": True,
     "episode": 1,
     "connections":[
        {"target":"The Door to Chthon (E1M6) Silver"},
        {"target":"The Door to Chthon (E1M6) Gold"}]},
    {"name": "The Door to Chthon (E1M6) Silver",
     "connects_to_hub": False,
     "episode": 1,
     "connections":[{"target":"The Door to Chthon (E1M6) Main"}]},
    {"name": "The Door to Chthon (E1M6) Gold",
     "connects_to_hub": False,
     "episode": 1,
     "connections":[{"target":"The Door to Chthon (E1M6) Main"}]},

    {"name": "The House of Chthon (E1M7) Main",
     "connects_to_hub": True,
     "episode": 1,
     "connections":[]},

    {"name": "Ziggurat Vertigo (E1M8) Main",
     "connects_to_hub": True,
     "episode": 1,
     "connections":[{"target":"Ziggurat Vertigo (E1M8) Silver"}]},
    {"name": "Ziggurat Vertigo (E1M8) Silver",
     "connects_to_hub": False,
     "episode": 1,
     "connections":[{"target":"Ziggurat Vertigo (E1M8) Main"}]},

    {"name": "The Installation (E2M1) Main",
     "connects_to_hub": True,
     "episode": 2,
     "connections":[
        {"target":"The Installation (E2M1) Gold"}]},
    {"name": "The Installation (E2M1) Silver",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[{"target":"The Installation (E2M1) Gold"}]},
    {"name": "The Installation (E2M1) Gold",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[
        {"target":"The Installation (E2M1) Main"},
        {"target":"The Installation (E2M1) Silver"}]},

    {"name": "The Ogre Citadel (E2M2) Main",
     "connects_to_hub": True,
     "episode": 2,
     "connections":[{"target":"The Ogre Citadel (E2M2) Gold"}]},
    {"name": "The Ogre Citadel (E2M2) Gold",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[]},

    {"name": "The Crypt of Decay (E2M3) Main",
     "connects_to_hub": True,
     "episode": 2,
     "connections":[{"target":"The Crypt of Decay (E2M3) Gold"}]},
    {"name": "The Crypt of Decay (E2M3) Gold",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[{"target":"The Crypt of Decay (E2M3) Main"}]},

    {"name": "The Ebon Fortress (E2M4) Main",
     "connects_to_hub": True,
     "episode": 2,
     "connections":[
        {"target":"The Ebon Fortress (E2M4) Silver"},
        {"target":"The Ebon Fortress (E2M4) Gold"}]},
    {"name": "The Ebon Fortress (E2M4) Silver",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[{"target":"The Ebon Fortress (E2M4) Main"}]},
    {"name": "The Ebon Fortress (E2M4) Gold",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[{"target":"The Ebon Fortress (E2M4) Main"}]},

    {"name": "The Wizard's Manse (E2M5) Main",
     "connects_to_hub": True,
     "episode": 2,
     "connections":[{"target":"The Wizard's Manse (E2M5) Gold"}]},
    {"name": "The Wizard's Manse (E2M5) Gold",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[{"target":"The Wizard's Manse (E2M5) Main"}]},

    {"name": "The Dismal Oubliette (E2M6) Main",
     "connects_to_hub": True,
     "episode": 2,
     "connections":[{"target":"The Dismal Oubliette (E2M6) Gold"}]},
    {"name": "The Dismal Oubliette (E2M6) Gold",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[{"target":"The Dismal Oubliette (E2M6) Main"}]},

    {"name": "The Underearth (E2M7) Main",
     "connects_to_hub": True,
     "episode": 2,
     "connections":[{"target":"The Underearth (E2M7) Gold"}]},
    {"name": "The Underearth (E2M7) Gold",
     "connects_to_hub": False,
     "episode": 2,
     "connections":[{"target":"The Underearth (E2M7) Main"}]},

    {"name": "Termination Central (E3M1) Main",
     "connects_to_hub": True,
     "episode": 3,
     "connections":[{"target":"Termination Central (E3M1) Gold"}]},
    {"name": "Termination Central (E3M1) Gold",
     "connects_to_hub": False,
     "episode": 3,
     "connections":[{"target":"Termination Central (E3M1) Main"}]},

    {"name": "The Vaults of Zin (E3M2) Main",
     "connects_to_hub": True,
     "episode": 3,
     "connections":[{"target":"The Vaults of Zin (E3M2) Silver"}]},
    {"name": "The Vaults of Zin (E3M2) Gold",
     "connects_to_hub": False,
     "episode": 3,
     "connections":[{"target":"The Vaults of Zin (E3M2) Silver"}]},
    {"name": "The Vaults of Zin (E3M2) Silver",
     "connects_to_hub": False,
     "episode": 3,
     "connections":[
        {"target":"The Vaults of Zin (E3M2) Main"},
        {"target":"The Vaults of Zin (E3M2) Gold"}]},

    {"name": "The Tomb of Terror (E3M3) Main",
     "connects_to_hub": True,
     "episode": 3,
     "connections":[{"target":"The Tomb of Terror (E3M3) Silver"}]},
    {"name": "The Tomb of Terror (E3M3) Silver",
     "connects_to_hub": False,
     "episode": 3,
     "connections":[{"target":"The Tomb of Terror (E3M3) Main"}]},

    {"name": "Satan's Dark Delight (E3M4) Main",
     "connects_to_hub": True,
     "episode": 3,
     "connections":[]},

    {"name": "The Wind Tunnels (E3M5) Main",
     "connects_to_hub": True,
     "episode": 3,
     "connections":[]},

    {"name": "Chambers of Torment (E3M6) Main",
     "connects_to_hub": True,
     "episode": 3,
     "connections":[{"target":"Chambers of Torment (E3M6) Silver"}]},
    {"name": "Chambers of Torment (E3M6) Silver",
     "connects_to_hub": False,
     "episode": 3,
     "connections":[
        {"target":"Chambers of Torment (E3M6) Main"},
        {"target":"Chambers of Torment (E3M6) Gold"}]},
    {"name": "Chambers of Torment (E3M6) Gold",
     "connects_to_hub": False,
     "episode": 3,
     "connections":[{"target":"Chambers of Torment (E3M6) Silver"}]},

    {"name": "The Haunted Halls (E3M7) Main",
     "connects_to_hub": True,
     "episode": 3,
     "connections":[]},

    {"name": "The Sewage System (E4M1) Main",
     "connects_to_hub": True,
     "episode": 4,
     "connections":[{"target":"The Sewage System (E4M1) Gold"}]},
    {"name": "The Sewage System (E4M1) Gold",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"The Sewage System (E4M1) Main"}]},

    {"name": "The Tower of Despair (E4M2) Main",
     "connects_to_hub": True,
     "episode": 4,
     "connections":[{"target":"The Tower of Despair (E4M2) Silver"}]},
    {"name": "The Tower of Despair (E4M2) Silver",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"The Tower of Despair (E4M2) Main"}]},

    {"name": "The Elder God Shrine (E4M3) Main",
     "connects_to_hub": True,
     "episode": 4,
     "connections":[
        {"target":"The Elder God Shrine (E4M3) Silver"},
        {"target":"The Elder God Shrine (E4M3) Gold"}]},
    {"name": "The Elder God Shrine (E4M3) Silver",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"The Elder God Shrine (E4M3) Main"}]},
    {"name": "The Elder God Shrine (E4M3) Gold",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"The Elder God Shrine (E4M3) Main"}]},

    {"name": "The Palace of Hate (E4M4) Main",
     "connects_to_hub": True,
     "episode": 4,
     "connections":[{"target":"The Palace of Hate (E4M4) Silver"}]},
    {"name": "The Palace of Hate (E4M4) Silver",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"The Palace of Hate (E4M4) Main"}]},

    {"name": "Hell's Atrium (E4M5) Main",
     "connects_to_hub": True,
     "episode": 4,
     "connections":[
        {"target":"Hell's Atrium (E4M5) Silver"},
        {"target":"Hell's Atrium (E4M5) Gold"}]},
    {"name": "Hell's Atrium (E4M5) Silver",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"Hell's Atrium (E4M5) Main"}]},
    {"name": "Hell's Atrium (E4M5) Gold",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"Hell's Atrium (E4M5) Main"}]},

    {"name": "The Pain Maze (E4M6) Main",
     "connects_to_hub": True,
     "episode": 4,
     "connections":[{"target":"The Pain Maze (E4M6) Gold"}]},
    {"name": "The Pain Maze (E4M6) Silver",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"The Pain Maze (E4M6) Gold"}]},
    {"name": "The Pain Maze (E4M6) Gold",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[
        {"target":"The Pain Maze (E4M6) Main"},
        {"target":"The Pain Maze (E4M6) Silver"}]},

    {"name": "Azure Agony (E4M7) Main",
     "connects_to_hub": True,
     "episode": 4,
     "connections":[{"target":"Azure Agony (E4M7) Silver"}]},
    {"name": "Azure Agony (E4M7) Silver",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"Azure Agony (E4M7) Main"}]},

    {"name": "The Nameless City (E4M8) Main",
     "connects_to_hub": True,
     "episode": 4,
     "connections":[
        {"target":"The Nameless City (E4M8) Silver"},
        {"target":"The Nameless City (E4M8) Gold"}]},
    {"name": "The Nameless City (E4M8) Silver",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"The Nameless City (E4M8) Main"}]},
    {"name": "The Nameless City (E4M8) Gold",
     "connects_to_hub": False,
     "episode": 4,
     "connections":[{"target":"The Nameless City (E4M8) Main"}]},

    {"name": "Shub-Niggurath's Pit (END) Main",
     "connects_to_hub": True,
     "episode": 5,
     "connections":[]},
]
